bookings/urls.py
from django.views import generic, View
from . import views
from django.urls import path


urlpatterns = [
   path('', views.index, name='home'),
   path('login.html', views.login, name='login'),
   path('Sign-up.html', views.signUp, name='Sign-up'),
   path('logged-in.html', views.loggedin, name='logged-in'),
   path('book-table.html', views.BookingTables.as_view(), name='book-table'),
   path('edit-booking/<booking_id>', views.edit_bookings, name='edit_booking'),
   path('delete/<booking_id>', views.deleteBooking, name='delete_booking'),
   path('view-bookings.html', views.view_bookings, name='view_bookings'),
]

restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from bookings import views

urlpatterns = [
    path("", include("bookings.urls")),
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('accounts/', include('allauth.urls')),
]

bookings/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.core.validators import MaxValueValidator, MinValueValidator

STATUS = ((0, "Occupied"), (1, "Ordered"))

class newBooking(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    pick_date = models.DateField()
    pick_time = models.TimeField()

    def __str__(self): 
        return f' {self.first_name} {self.last_name} booked a table on the {self.pick_date} {self.pick_time} '

class newbookTable(models.Model):
    Booking = models.ForeignKey(newBooking, on_delete=models.CASCADE, related_name="tables")
    people = models.IntegerField(validators=[
            MaxValueValidator(20),
            MinValueValidator(1)
        ])

    def __str__(self):
        return f'{self.Booking} {self.people} guests will be attending. '


class TableInverntory(models.Model):
    Tablecount = models.IntegerField(default=20)
    Tables_available = models.BooleanField(default=False)

    Tables = 0

templates/book-table.html
{% load static %}

{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/35936358ad.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-growl/1.0.0/jquery.bootstrap-growl.min.js"> </script>
    <script src="https://code.jquery.com/jquery-3.6.0.js"
        integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
    </script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'assets/icon.png' %}">
    <title> Sodja </title>
</head>

<body>

    <!-- This is my main nav bar, it has a logout link and it has a Book-Tables link that is active once the user enters this page. -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark opacity-75">
        <div class="container-fluid">
            <a class="navbar-brand mb-0 h1" href="./logged-in.html">Sodja Resturaunt
                <img src="{% static 'assets/icon.png' %}" alt="icon" width="64" height="64">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarScroll">
                <ul class="navbar-nav ms-auto my-2 my-lg-0" style="--bs-scroll-height: 100px;">
                    <li class="nav-item nav-item-header">
                        <a class="nav-link nav-link-header" aria-current="page"
                            href="{% url 'account_logout' %}">Logout</a>
                    </li>
                    <li class="nav-item nav-item-header">
                        <a class="nav-link nav-item-header active" href="">Book Tables</a>
                    </li>
                    <li>
                        <a class="nav-link nav-item-header" href="./view-bookings.html">My bookings</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- This is my main-content of this page.I set the background color to white so that the content would stand out.   -->
    <div style="background-color:#fff;">
      
        <div class="container mt-5 col-md-6" style="background-color: #fff; border: 3px solid grey;">
            <div class="row-12 mb-5">
                <h1 class="text-center" style="font-size: 55px; color: grey; font-weight: bold; letter-spacing: 1px;">
                    Book A Table </h1>
                <hr>
            </div>
            <!-- Once the user submites the form and validation is successful, this alert will pop-up instead of the form. So that the user understands
            that the form has been sent successfully.
            -->
            {% if Table_booked == True %}
            <div class="alert alert-success" role="alert">
                <h4 class="alert-heading">Well done!</h4>
                <p>You have successfully booked a table with sodja restaurant. If you need anything else please feel free to contact us at email: Sodja@gmail.com or contact us at - mobile@ +353 0894786690.</p>
                <hr>
                <p class="mb-0">Be sure to cancel or rearrange the date if you feel like you cannot attend, contact us for more information.</p>
              </div>
              <div>
                  <h2> Your Bookings: </h2>
                  <table>
                    
                  {% for booking in allBookings %}
                  <hr style="Visibility: hidden;">
                    <tr>
                        <td>
                        <p> {{ booking }}</p>
                        <a href="/delete/{{ booking.id }}" class="btn btn-danger btn-md " tabindex="-1" role="button">Cancelle Reservation</a>
                            <a href="/edit-booking/{{ booking.id }}" class="btn btn-info btn-md " tabindex="-1" role="button">Edit Reservation</a>
                         <hr style="Visibility: hidden;">
                        </td>
                     </tr>
                </table>
                {% endfor %}
              </div>
              {% else %}
            <form class="row g-3" method="POST" >
                <div class="col-md-6">
                    <label for="id_first_name" class="form-label" style="font-weight: bold;">First Name
                    </label>
                        {{ form.first_name }}
                        {% csrf_token %}
                </div>
                <div class="col-md-6">
                    <label for="id_last_name" class="form-label" style="font-weight: bold;">Last name</label>
                   
                    {{ form.last_name }}
                    {% csrf_token %}
                </div>
                <!-- This errorMessage pops up whenever their is a problem with the form validation. This is for the user to know what's wrong. -->
                {% if errorMessage %}
                <div class="alert alert-danger" role="alert">
                    {{errorMessage}}
                </div>
                    {% endif %}

                <div class="col-md-6 mt-5">
                    <label for="id_pick_date" class="form-label" style="font-weight: bold;">Pick Date</label>
                    
                    {{ form.pick_date }}
                    {% csrf_token %}
                </div>
                <div class="col-md-6 mt-5">
                    <label for="id_pick_time" class="form-label" style="font-weight: bold;">Pick Time</label>
                   
                    {{ form.pick_time }}
                    {% csrf_token %}
                </div>
                <div class="col-12 mt-5">
                    <label for="id_people" class="mb-3" style="font-weight: bold;">How many people are attending?</label>
                    {{ form2.people }}
                    {% csrf_token %}
                    <p class="mt-3"> <strong>Note:</strong> keep the people between 1-20 or else you will have to restart your form. (max 20 people) </p>
                    <p class="mt-3">Only 5 people per table is allowed, if you are coming with
                        more than 5 people please note that you will be setted in different tables. </p>
                </div>
                <div class="col-12 mt-3">
                    <button type="submit" class="btn btn-primary mb-3">Submit Form</button>
                </div>
            </form>
            {% endif %}
            <hr style="Visibility: hidden;">
        </div>
        <!-- They's hr elements are to make space between the content and the footer. -->
        <hr style="Visibility: hidden;">
        <hr style="Visibility: hidden;">
        <hr style="Visibility: hidden;">
        <hr style="Visibility: hidden;">
        <hr style="Visibility: hidden;">
    </div>
    <!-- This footer is the same like in the base.html file but the difference is in the links, Instead of Top, About and Menu i put 
    Facebook, Instagram, Youtube and Twitter because dose are supposed to be my Social links. -->
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top bg-dark mt-auto"
        id="footer">
        <p class="col-md-4 mb-0 red-text">&copy; 2022 Sodja Company Resturaunt, Inc</p>

        <a href="/logged-in.html"
            class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
            <img src="{% static 'assets/icon.png' %}" alt="icon" width="64" height="64">
        </a>

        <ul class="nav col-md-4 justify-content-end">
            <li class="nav-item"><a href="https://www.facebook.com/login/device-based/regular/login/?login_attempt=1" class="nav-link px-2 red-text">Facebook</a></li>
            <li class="nav-item"><a href="https://www.instagram.com/" class="nav-link px-2 red-text">Instagram</a></li>
            <li class="nav-item"><a href="https://www.youtube.com/" class="nav-link px-2 red-text">Youtube</a></li>
            <li class="nav-item"><a href="https://twitter.com/?lang=en-ie" class="nav-link px-2 red-text">Twitter</a></li>
        </ul>
    </footer>
</body>

</html>

templates/edit-booking.html
{% load static %}

{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/35936358ad.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
        integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-growl/1.0.0/jquery.bootstrap-growl.min.js"> </script>
    <script src="https://code.jquery.com/jquery-3.6.0.js"
        integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
    </script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" href="{% static 'assets/icon.png' %}">
    <title> Sodja </title>
</head>

<body>

    <!-- This is my main nav bar, it has a logout link and it has a Book-Tables link that is active once the user enters this page. -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark opacity-75">
        <div class="container-fluid">
            <a class="navbar-brand mb-0 h1" href="/logged-in.html">Sodja Resturaunt
                <img src="{% static 'assets/icon.png' %}" alt="icon" width="64" height="64">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarScroll">
                <ul class="navbar-nav ms-auto my-2 my-lg-0" style="--bs-scroll-height: 100px;">
                    <li class="nav-item nav-item-header">
                        <a class="nav-link nav-link-header" aria-current="page"
                            href="{% url 'account_logout' %}">Logout</a>
                    </li>
                
                    <li class="nav-item nav-item-header">
                        <a class="nav-link nav-link-header" aria-current="page"
                            href="/logged-in.html">Back</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- This is my main-content of this page.I set the background color to white so that the content would stand out.   -->
    <div style="background-color:#fff;">
      
        <div class="container mt-5 col-md-6" style="background-color: #fff; border: 3px solid grey;">
            <div class="row-12 mb-5">
                <h1 class="text-center" style="font-size: 55px; color: grey; font-weight: bold; letter-spacing: 1px;">
                    Edit Reservation </h1>
                <hr>
            </div>

            <form class="row g-3" method="POST">
                <div class="col-md-6">
                    <label for="id_first_name" class="form-label" style="font-weight: bold;">Update First Name</label>
                    {{ form.first_name }}
                    {% csrf_token %}
                </div>
                <div class="col-md-6">
                    <label for="id_last_name" class="form-label" style="font-weight: bold;"> Update Last name</label>
                   
                    {{ form.last_name }}
                    {% csrf_token %}
                </div>
                <!-- This errorMessage pops up whenever their is a problem with the form validation. This is for the user to know what's wrong. -->
                {% if errorMessage %}
                <div class="alert alert-danger" role="alert">
                    {{errorMessage}}
                </div>
                    {% endif %}

                <div class="col-md-6 mt-5">
                    <label for="id_pick_date" class="form-label" style="font-weight: bold;">Update Date</label>
                    
                    {{ form.pick_date }}
                    {% csrf_token %}
                </div>
                <div class="col-md-6 mt-5">
                    <label for="id_pick_time" class="form-label" style="font-weight: bold;">Update Time</label>
                   
                    {{ form.pick_time }}
                    {% csrf_token %}
                </div>
                <div class="col-12 mt-3">
                    <button type="submit" class="btn btn-primary mb-3">Update Form</button>
                </div>
            </form>

            <hr style="Visibility: hidden;">
        </div>
        <!-- They's hr elements are to make space between the content and the footer. -->
        <hr style="Visibility: hidden;">
        <hr style="Visibility: hidden;">
        <hr style="Visibility: hidden;">
        <hr style="Visibility: hidden;">
        <hr style="Visibility: hidden;">
    </div>
    <!-- This footer is the same like in the base.html file but the difference is in the links, Instead of Top, About and Menu i put 
    Facebook, Instagram, Youtube and Twitter because dose are supposed to be my Social links. -->
    <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top bg-dark mt-auto"
        id="footer">
        <p class="col-md-4 mb-0 red-text">&copy; 2022 Sodja Company Resturaunt, Inc</p>

        <a href="/logged-in.html"
            class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
            <img src="{% static 'assets/icon.png' %}" alt="icon" width="64" height="64">
        </a>

        <ul class="nav col-md-4 justify-content-end">
            <li class="nav-item"><a href="https://www.facebook.com/login/device-based/regular/login/?login_attempt=1" class="nav-link px-2 red-text">Facebook</a></li>
            <li class="nav-item"><a href="https://www.instagram.com/" class="nav-link px-2 red-text">Instagram</a></li>
            <li class="nav-item"><a href="https://www.youtube.com/" class="nav-link px-2 red-text">Youtube</a></li>
            <li class="nav-item"><a href="https://twitter.com/?lang=en-ie" class="nav-link px-2 red-text">Twitter</a></li>
        </ul>
    </footer>
</body>

</html>

templates/index.html
{% extends "base.html" %}
{% load static %}
<!-- index.html is my home page, the first page the user see's when they load in. -->
<!-- This is my image and container that is at the top of the page -->
<div class="container-fluid bg-dark bg-gradient">
    <div id="resturanunt-image-container">
        <img src="{% static 'assets/edit3.jpg' %}" class="img-fluid rounded mx-auto d-block" alt="Resturaunt"
            id="resturanunt-image">
    </div>
    <hr>
    <hr>
</div>
<!-- This is my container, Columns and rows (grid system) that i use for my about section -->
<!-- About Section -->
<div class="container-fluid" style="background-color: rgba(255, 255, 255, 0.678);">
    <div class="container mb-5 mt-5" style="border: 1px solid #fff; background-color: rgb(55, 57, 65);">
        <div class="row" style="border: 1px solid #fff;">
            <div class="col-12 pt-3">
                <h1 class="text-center display-2" id="About-Us-id" style="color: #fff;"> Something About Us <img
                        src="{% static 'assets/icon.png' %}" alt="icon" width="64" height="64"></h1>
            </div>
        </div>
        <div class="row p-5 g-5">
            <div class="col-sm-6">
                <div class="p-3">
                    <h1 class="text-center" style="color: #fff;">Sodja Resturaunt</h1>
                    <p style="color: #fff;"> We promise a
                        romantic setting for you and your guessed to dine in. We offer a
                        special menu that was selected by our head chef that should complement your romantic
                        environment.
                        We have Comtrouble chairs with
                        nicely dressed tables and a bar in our
                        restaurant. We also have a decorated lounge area
                        if for any reason you had to wait for your tables to get pre-pared.
                        Also something interesting about our bar - our bar got nominated for Best restaurant Bar of
                        the Year 2022.
                        At Arkle Bar, each
                        and every dish is freshly prepared and cooked and is a dedication to our promise to use only
                        the best quality ingredients.
                        Dine in our exquisite, stylish Arkle Bar boasting its own unique style and ambiance, the
                        perfect choice for food lovers and wine connoisseurs alike. Sink back into our plush 1920s
                        interiors where you may choose to sip on a revitalising cocktail created by our in-house
                        mixologist, savour a fine wine, whiskey or brandy.
                    </p>
                </div>
            </div>

            <div class="col-sm-6">
                <div class="p-3">
                    <h1 class="text-center" style="color: #fff;">Restaurants in Maynooth</h1>
                    <p style="color: #fff;"> With some of the best restaurants in Maynooth County Kildare, the
                        Glenroyal Hotel with Brady's Bar, The Sodja Restaurant & Vine Market Cafe promises to
                        delight both the casual & seasoned diners alike. Visitors and guests can look forward to a
                        variety of dishes while also catering for healthier options.
                        To Find Us -
                        Just a stroll from Maynooth Town, 20 minutes from Dublin, and less than 40 minutes from the
                        airport.

                        With excellent national rail & bus and motorway connections on our door step, we're close to
                        everywhere! You can book your parties / weddings and other such events with us using our
                        contact line + 353 0894787029 or you can email us at SodjaResturant@gmail.com, For more
                        information about travel and site's of
                        Maynooth please come visit <a href="https://maynoothtown.ie/" target="_blank">https://maynoothtown.ie/</a>
                        where you can find more excluseive information about our Town.
                    </p>
                </div>
            </div>
        </div>
    </div>
    <hr>

</div>
<!-- End of About Section -->

<!-- Menu Section -->
<!-- I used a grid system for my menu section  -->
<div class="container-fluid" style="background-color: rgb(255, 255, 255);">
    <div class="container mb-5 mt-5" style="border: 1px solid #fff; background-color: rgb(255, 255, 255);">
        <div class="row" style="border: 1px solid #fff;">
            <div class="col-12 pt-3">
                <h1 class="text-center display-2" id="Menu-id" style="color: rgb(0, 0, 0);"> Menu <img
                        src="{% static 'assets/icon.png' %}" alt="icon" width="64" height="64"></h1>
            </div>
        </div>
        <hr>
        <div class="row p-5 g-5">
            <div class="col">
            <img src="{% static 'assets/steak.jpg' %}" class="" style="border: 3px solid black;" alt="Steak-image" width="360" height="360">   
            <p class="text-center" style="padding: 10px; font-size: 20px; font-weight: bold;">
                Steak | price: €14.55
            </p> 
            </div>
            <div class="col">
                <img src="{% static 'assets/ham-cheese-sandwich.jpg' %}" class="" style="border: 3px solid black;" alt="Ham-Cheese-image" width="360" height="360">   
            <p class="text-center" style="padding: 10px; font-size: 20px; font-weight: bold;">
                Ham-Cheese Sandwich | price: €8.55
            </p> 
            </div>
            <div class="col">
                <img src="{% static 'assets/salmon.jpg' %}" class="" style="border: 3px solid black;" alt="Salmon-image" width="360" height="360">   
            <p class="text-center" style="padding: 10px; font-size: 20px; font-weight: bold;">
                Salmon | price: €14.55
            </p> 
            </div>

        </div>
        <div class="row p-5 g-5">
            <div class="col">
                <img src="{% static 'assets/chicken-wings.jpg' %}" class="" style="border: 3px solid black;" alt="Chicken-Wings-image" width="360" height="360">   
                <p class="text-center" style="padding: 10px; font-size: 20px; font-weight: bold;">
                    Chicken-Wings | price: €10.25
                </p> 
            </div>
            <div class="col">
                <img src="{% static 'assets/burger-fries.jpg' %}" class="" style="border: 3px solid black;" alt="Burger-fries-image" width="360" height="360">   
                <p class="text-center" style="padding: 10px; font-size: 20px; font-weight: bold;">
                    Burger-fries | price: €9.25
                </p> 
            </div>
            <div class="col">
                <img src="{% static 'assets/soup.jpg' %}" class="" style="border: 3px solid black;" alt="Soup-image" width="360" height="360">   
                <p class="text-center" style="padding: 10px; font-size: 20px; font-weight: bold;">
                    Soup | price: €7.55
                </p> 
            </div>
            

        </div>
        <div class="row p-5 g-5">
            <div class="col">
                <img src="{% static 'assets/lamb-chops.jpg' %}" class="" style="border: 3px solid black;" alt="lamb-chops-image" width="360" height="360">   
                <p class="text-center" style="padding: 10px; font-size: 20px; font-weight: bold;">
                    lamb-chops | price: €15.55
                </p> 
            </div>
            <div class="col">
                <img src="{% static 'assets/pork-chops.jpg' %}" class="" style="border: 3px solid black;" alt="pork-chops-image" width="360" height="360">   
                <p class="text-center" style="padding: 10px; font-size: 20px; font-weight: bold;">
                    pork-chops & Veg | price: €14.55
                </p> 
            </div>
            <div class="col">
                <img src="{% static 'assets/vegan-wraps.jpg' %}" class="" style="border: 3px solid black;" alt="Vegan-Wraps-image" width="360" height="360">   
                <p class="text-center" style="padding: 10px; font-size: 20px; font-weight: bold;">
                    Vegan-Wraps | price: €9.55
                </p> 
            </div>

        </div>
        <div class="row p-5 g-5">
            <div class="col">
                <img src="{% static 'assets/pancakes.jpg' %}" class="" style="border: 3px solid black;" alt="Pancakes-image" width="360" height="360">   
                <p class="text-center" style="padding: 10px; font-size: 20px; font-weight: bold;">
                    Pancakes | price: €10.55
                </p> 
            </div>
            <div class="col">
                <img src="{% static 'assets/sushi.jpg' %}" class="" style="border: 3px solid black;" alt="Sushi-image" width="360" height="360">   
                <p class="text-center" style="padding: 10px; font-size: 20px; font-weight: bold;">
                    Sushi | price: €11.95
                </p> 
            </div>
            <div class="col">
                <img src="{% static 'assets/pizza.jpg' %}" class="" style="border: 3px solid black;" alt="Pizza-image" width="360" height="360">   
                <p class="text-center" style="padding: 10px; font-size: 20px; font-weight: bold;">
                    Pizza | price: €9.55
                </p> 
            </div>

        </div>
    </div>
    <hr>
</div>
<!-- End Of Menu Section -->
<!-- The footer is in my 'base.html' template. -->